### ISSUE TITLE
Get chat history path from .env file

### ISSUE THREAD

**Issue by debevv** [Alfex4936/Bard-rs#13]
Hi, it would be nice to be able to specify the path of the history file inside the `.env` file, so one can simply call `bard-rs` and be always sure to have his/her chat saved.
Something like `HISTORY` maybe?

**Comment by Alfex4936** [comment]
I thought setting the default behavior of the application to not save chat histories for quick usage sessions.

However, it would be useful to have an option in the .env file, labeled `HISTORY`, which when activated, enables automatic chat history saving.

By default, this feature should remain inactive unless explicitly enabled by the user.

Gonna work on it soon!
