### ISSUE TITLE
Issues with text input

### ISSUE THREAD

**Issue by Alanon202** [Alfex4936/Bard-rs#15]
I’ve been using bard-rs for some time and believe this behaviour began when it was "geminified". Ever since then I’ve been trying to figure out why I’ve been making tons of mistakes in this app, and only now have resolved to sit down and create some sort of report. I’ve tested this on Alacritty and URxvt on Arch Linux, in both terminals bard-rs is the only terminal app that exhibits this behaviour. 

In short, text input seems bugged out somehow, I’ll try to describe the phenomenon with a simple example with some screenshots.

1. In the screenshot below you’ll see the word "Text" as typed in on a fresh, untouched instance. 
![1](https://github.com/user-attachments/assets/b691f78d-155a-4f3a-95da-8451c096e939)

2. As soon as I delete the letter "t", a space is created in front of the word, the whole text shifts one space to the right, and the letter "x" becomes selected:
![2](https://github.com/user-attachments/assets/1196cd22-f1bf-4600-a85d-c446faad0ad8)

3. If I now want to type the letter "t" again to complete the word, it will not type it next to "x" but overwrite that letter instead, giving me "Tet" as the result:
![3](https://github.com/user-attachments/assets/2a0fe5c5-093d-4220-b3ae-bf25c70efbe2)

4. If I try to compensate for this annoyance by again typing "x" over the current "x" and then "t" again in order to get the word "Text", the text in the terminal will show correctly, but Gemini’s output will actually display double letters, i.e. "Texxt":
![4](https://github.com/user-attachments/assets/b664decd-cb10-4f8c-a994-ff32e91eb6f2)

So it looks like the terminal somehow isn’t syncing with the text that is typed and that is sent to Gemini, and unless one types everything perfectly in one go, one either has to type normally and live with the garbled prompt, or try to create a literate prompt and end up with a bunch of doubled letters.

I’m open to any further debug steps. I find bard-rs extremely useful but these input snags are quite a chore to put up with.

**Comment by Alfex4936** [comment]
Hello! Thank you for your detailed report.

It appears that the issue with rustyline might be caused by asynchronous tasks interfering with the terminal's input buffer or prompt rendering.

I will investigate this further and provide an update as soon as possible.

Thank you for your patience!

**Comment by Alfex4936** [comment]
I attempted to resolve the issue by giving up the Completer feature and the colored symbol for user input part, as they were interfering with the cursor position and I was unable to pinpoint the exact cause.

Please let me know if this solution works for you!

![image](https://github.com/user-attachments/assets/a49f8a74-7dd2-451f-a3ad-81017aa9f8fb)

**Comment by Alanon202** [comment]
Works perfectly now! :) I wasn’t even aware of the completer functionality, so for me it’s no loss whatsoever.
If you’d like to test different solutions later on, feel free to ping me, I’d be glad to test it out.
