### ISSUE TITLE
Can't use arrow key in bard-rs shell for nav

### ISSUE THREAD

**Issue by noman-test** [Alfex4936/Bard-rs#2]
Arrow key will been ANSI escape code when input that in bard-rs interactive shell.

**Comment by Alfex4936** [comment]
May I ask which terminal are you using so I can test correctly?

Thanks in advance

**Comment by noman-test** [comment]
macOS Ventura 13.2.1
terminal: Alacritty
But other terminals also have this problem.

**Comment by Alfex4936** [comment]
Can you try git version?

```bash
git clone https://github.com/Alfex4936/Bard-rs

cd Bard-rs

echo "SESSION_ID=your" > .env

cargo run -- -e .env
```

**Comment by noman-test** [comment]
Arrow key in git version works. Thx
