### ISSUE TITLE
Regarding UI/UX

### ISSUE THREAD

**Issue by Code-acious** [Alfex4936/Bard-rs#3]
![Screenshot_2023-05-18_15-05-51](https://github.com/Alfex4936/Bard-rs/assets/85301801/f10838d7-1e1b-4e45-a057-dd7bfb1144d7)

Can you make UI of bard-rs looks like as above, because It looks more clean and readable also taking notes is easier.

It would great if you add that arrow.

**Comment by Alfex4936** [comment]
![image](https://github.com/Alfex4936/Bard-rs/assets/2356749/c4c78187-299f-4ba2-8ed4-bb857713de50)


this would work?

**Comment by Code-acious** [comment]
Yooooooooo ❤️❤️❤️❤️❤️❤️❤️❤️

You're my bro!

Thanks Thankyou so much.Awesome

**Comment by Code-acious** [comment]
Please tell how to update with cargo install not git pull

**Comment by Alfex4936** [comment]
Just updated through cargo so let me know if it works well :)

**Comment by Code-acious** [comment]
How to update with cargo I don't want to use git

**Comment by Alfex4936** [comment]
`cargo install bard-rs` will update to latest version automatically

**Comment by Code-acious** [comment]
Awesome, thanks!

**Comment by Code-acious** [comment]
![Screenshot_2023-05-19_14-42-05](https://github.com/Alfex4936/Bard-rs/assets/85301801/5f76bf56-e937-4e8b-9d7c-0009a36826e1)

Works like a charm, Thanks ^_^! :1st_place_medal:

**Comment by Code-acious** [comment]
![CVyf](https://github.com/Alfex4936/Bard-rs/assets/85301801/f286e997-5917-4773-b9f6-864d353f7740)

Can you add following gif animation to "bard: thinking...." ---> bard:thinking <gif> instead of static dots add colourfull dots that jumps as in gif at the end. If gif not possible atleast add colourfull dots or any other loading animation.

**Comment by Alfex4936** [comment]
hmm adding a loading animation would be indeed difficult task but I have an idea so will try to work on it in next weekdays :)

**Comment by Alfex4936** [comment]
I am still figuring out the most appropriate way to update progress bar for POST function.

![output](https://github.com/Alfex4936/Bard-rs/assets/2356749/134e452b-a2df-4a90-b624-bc2dc8b5defb)

**Comment by Code-acious** [comment]
Take your time, currently it looks a little jittery, nonetheless good
effort. Hey what about a solid rectangle bar or just a solid circle but
with smooth RGB color changing effect. Progress bar defines if something is
updating which looks a little out of context.

Thankyou for ur effrt

**Comment by Alfex4936** [comment]
this would be enough I think

![output](https://github.com/Alfex4936/Bard-rs/assets/2356749/946381d5-20ae-4c34-aa08-7cec9e111bfc)

or can make like google's loading bar

![g](https://github.com/Alfex4936/Bard-rs/assets/2356749/d63608e8-8bf8-4fd5-a0f8-d613d8b8b99a)

**Comment by inquire** [comment]
Also for code it would be nice to print it in a way where there is syntax highlighting!

**Comment by Code-acious** [comment]
Have you updated the package because for me

cargo install bard-rs says already latest version.

I did a force update by cargo install --force bard-rs but still
not working. Same old bard thinking... is there no progress bar.

**Comment by Alfex4936** [comment]
@inquire I'm considering implementing it with `syntect`, although I'm hesitant because `bard-rs` supports real-time saving to a markdown file so idk yet

@Code-acious hasn't been released yet. I've encountered a bug in most terminal apps where the progress bar gets left behind when changing the terminal size, particularly when using the `indicatif` crate. However, I plan to release it soon, featuring a loading bar style inspired by Google, which I showcased in my previous comment.

**Comment by Code-acious** [comment]
Yo the Google inspired loading animation is gr8. That's what I was telling you. Please implement that only, can't wait to try it. 🏅🏅🏅🏅

**Comment by Code-acious** [comment]
I fell betrayed where are my dots u showed me 🥺🥺🥺🥺. I got circling bar animation. Anyways good effort 🤧🤧🤧🤧.

**Comment by Alfex4936** [comment]
Haha thanks but I had to choose most compatible characters (just / \) for common terminals.

But you can change it by changing `LOADING_CHARS` with your custom chars or `tick_chars` I left in my code such as  // let tick_chars = "○○◔◔◑◑◕◕●●◕◕◑◑◔◔ ";

Then you can `cargo install --path .` to install globally.

**Comment by Code-acious** [comment]
Yeah 😀 I know, I myself was concerned about will the characters support
for my terminal.

Anyways are you testing tgpt (Bai Chat terminal client)? If not you should
because in recent update it added a really cool feature where you can type
long prompts and if u have done spelling error or want to add something to
your prompt you can do it on the go which is was possible earlier and not
supported in bard-rs. It adds a little text editor. Basically u can now
move cursor with arrow keys.

You can find tgpt-bin in AUR or on GitHub author is andrew-me. Thanks.

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by demmorou** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
kirtangajjar, @caentzminger, @krisjpi, @afewnotes, @atlasstrategic, @ThalKod, @udit-gulati, @AgusVargas, @dwojcik92, @DuncanBetts, @nanspro, @mschwers, @21998524, @ytfei, @basgir, @gwthompson, @keeganskeate, @Cj-bc, @blocksherpa, @vinayakathavale

**Comment by Code-acious** [comment]
Thanks for all your support 💓.
