### ISSUE TITLE
Bard CLI emoticon bug

### ISSUE THREAD

**Issue by Code-acious** [Alfex4936/Bard-rs#4]
![Screenshot_2023-05-20_02-56-02](https://github.com/Alfex4936/Bard-rs/assets/85301801/18184619-7530-43c7-a886-da6808624b4c)

Bard-rs is unable to recognize or provide info regarding emoticons ending with parentheses such as :-), :-(, :{, :-[ . Is it the limitation of terminal? Although :-> :-< works fine.

**Comment by Alfex4936** [comment]
Thank you for the issue! Fixed with new command :)

`!show` to see all Bard's answers for the last message

![image](https://github.com/Alfex4936/Bard-rs/assets/2356749/5a542a25-eb9f-41a6-a081-d5d3586e1faf)
