### ISSUE TITLE
Calling "unwrap"

### ISSUE THREAD

**Issue by 7Moses** [Alfex4936/Bard-rs#7]
I am getting this error

╭─ Bard
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/moses/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bard-rs-1.2.0/src/main.rs:501:86
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: bard_rs::main::{{closure}}
   4: bard_rs::main

Line 501 is

                    let response_content = response.get("content").unwrap().as_str().unwrap();

I am using this for guidance

"Panicked at 'called `Option::unwrap()` on a `None` value'. What is wrong?" reddit, 4 July 2023, www.reddit.com/r/rust/comments/j5pvi3/panicked_at_called_optionunwrap_on_a_none_value.

See Lucretiel> Whenever you call unwrap, you're essentially promising that the value in the Option is not None, with the penalty that if it is, you crash the program. If you have an Option that might be None, the correct way to handle it is with a match, which is essentially the rust version of switch …

Has anyone got any guidance on this,  … 

How to edit 

Line 501>
                    let response_content = response.get("content").unwrap().as_str().unwrap();

Thanks

p.s. Beautiful work on bard-rs,

**Comment by Alfex4936** [comment]
![image](https://github.com/Alfex4936/Bard-rs/assets/2356749/8edd0462-1ae5-409b-8009-8729f5e52bc8)

Sorry for the late update! Just fixed the issue 👍 

Please update to v1.2.1 by `cargo install bard-rs`

Thank you, have a nice day :)

**Comment by 7Moses** [comment]
Excellent work by you, Thank you,
