### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by pan-szymanowski** [Alfex4936/Bard-rs#8]
OS Debian 11

1. First way of install:
>cargo install bard-rs

Updating crates.io index
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

2. Second way:
>cargo build --release

error: failed to parse manifest at `/home/jes/Bard-rs/Cargo.toml`
Caused by:
  failed to parse the `edition` key
Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown

**Comment by Alfex4936** [comment]
Can you try this?: https://www.reddit.com/r/rust/comments/sjoht3/receiving_error_supported_edition_values_are_2015/

**Comment by pan-szymanowski** [comment]
Perfect! Thank you so much. Please close this issue.
